Jake-brian
codefellows-seattle-301d24/09-sql-joins-relations pull request #7
Opened 2017-09-22 21:32 UTC by Cloud887

#### Single-line Summary
**Today, Jacob and Brian paired together. It took about 60 minutes**

#### Reflect and summarize on your process for each `TODO` item :  
 1. Wrote SQL queries that interacted with the AJAX calls on the front end and the database on the backend to do things like getting data to post, update data to the database and to delete data from the database

#### Checklist (before submitting, fill in each set of square brackets with an 'x')
- [x] I have entered the Pull Request title in the format of "Jacob-Brian"
- [x] This PR includes commits from both myself and my partner; e.g. We followed good pair programming practices by switching driver/navigator roles.
- [x] There is no extraneous, unrelated code included in this PR.
- [x] We have summarized our `TODO:` process above.

2017-09-22 21:33 UTC, Cloud887 commented
Drove mainly on my computer since the previous one was mostly on Brians computer for the last BLOG

2017-09-25 20:00 UTC, han8909227 requested changes

2017-09-25 20:00 UTC, han8909227 commented on jake-brian/starter-code/server.js
> +    'INSERT INTO author (author, "authorUrl") VALUES ($1, $2) ON CONFLICT DO NOTHING;', // DONE: Write a SQL query to insert a new author, ON CONFLICT DO NOTHING
In your SQL check the name of the author table, author or authors?

2017-09-25 20:00 UTC, han8909227 commented on jake-brian/starter-code/server.js
> +app.post('/articles', function(request, response) {
The insertRecord() method is not working, problems are in one of the query. Ensure the method is working by follow the instructions here https://github.com/codefellows-seattle-301d24/09-sql-joins-relations/blob/master/CRUD-testing.md 
(after insert refresh page the new article jibli jiber should appear first), get this working and re-submit for full credit.

2017-09-25 23:42 UTC, merged